src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: "user")]

class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    #[Groups(['user:list', 'user:item'])]
    private ?int $id = null;

    #[ORM\Column(type: Types::STRING, unique: true)]
    #[Assert\NotBlank]
    #[Assert\Length(min: 2, max: 100)]
    #[Groups(['user:list', 'user:item'])]
    private ?string $username = null;

    #[ORM\Column(type: Types::STRING, unique: true)]
    #[Assert\Email]
    #[Groups(['user:list', 'user:item'])]
    private ?string $email = null;

    #[ORM\Column(type: Types::STRING)]
    private ?string $password = null;

    #[ORM\Column(type: Types::JSON)]
    private array $roles = [];

    #[ORM\OneToMany(mappedBy: "owner", targetEntity: BigFootSighting::class)]
    #[Groups(['user:item'])]
    private Collection $bigFootSightings;

    #[ORM\OneToMany(mappedBy: "owner", targetEntity: Comment::class)]
    #[Groups(['user:item'])]
    private Collection $comments;

    #[ORM\Column(type: 'datetime')]
    #[Groups(['user:list', 'user:item'])]
    private \DateTimeInterface $agreedToTermsAt;

    public function __construct()
    {
        $this->bigFootSightings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): void
    {
        $this->email = $email;
    }


    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        // guarantees that a user always has at least one role for security
        if (empty($roles)) {
            $roles[] = 'ROLE_USER';
        }

        return array_unique($roles);
    }

    /**
     * @param string[] $roles
     */
    public function setRoles(array $roles): void
    {
        $this->roles = $roles;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): void
    {
        $this->password = $password;
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * {@inheritdoc}
     */
    public function getSalt(): ?string
    {
        // We're using bcrypt in security.yaml to encode the password, so
        // the salt value is built-in and you don't have to generate one
        // See https://en.wikipedia.org/wiki/Bcrypt

        return null;
    }

    /**
     * Removes sensitive data from the user.
     *
     * {@inheritdoc}
     */
    public function eraseCredentials(): void
    {
        // if you had a plainPassword property, you'd nullify it here
        // $this->plainPassword = null;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @return Collection|BigFootSighting[]
     */
    public function getBigFootSightings(): Collection
    {
        return $this->bigFootSightings;
    }

    public function addBigFootSighting(BigFootSighting $bigFootSighting): self
    {
        if (!$this->bigFootSightings->contains($bigFootSighting)) {
            $this->bigFootSightings[] = $bigFootSighting;
            $bigFootSighting->setOwner($this);
        }

        return $this;
    }

    public function removeBigFootSighting(BigFootSighting $bigFootSighting): self
    {
        if ($this->bigFootSightings->contains($bigFootSighting)) {
            $this->bigFootSightings->removeElement($bigFootSighting);
            // set the owning side to null (unless already changed)
            if ($bigFootSighting->getOwner() === $this) {
                $bigFootSighting->setOwner(null);
            }
        }

        return $this;
    }

    public function getAvatarUrl(): string
    {
        return sprintf('https://avatars.dicebear.com/4.5/api/human/%s.svg?mood[]=happy', $this->getEmail());
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function getAgreedToTermsAt(): ?\DateTimeInterface
    {
        return $this->agreedToTermsAt;
    }

    public function setAgreedToTermsAt(\DateTimeInterface $agreedToTermsAt): self
    {
        $this->agreedToTermsAt = $agreedToTermsAt;

        return $this;
    }

    public function getUserIdentifier(): string
    {
        return $this->username;
    }

    public function __serialize(): array
    {
        // add $this->salt too if you don't use Bcrypt or Argon2i
        return [$this->id, $this->username, $this->password];
    }

    /**
     * @param array{int|null, string, string} $data
     */
    public function __unserialize(array $data): void
    {
        // add $this->salt too if you don't use Bcrypt or Argon2i
        [$this->id, $this->username, $this->password] = $data;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\BigFootSighting;
use App\Entity\User;
use App\Form\AgreeToUpdatedTermsFormType;
use App\GitHub\GitHubApiHelper;
use App\Repository\BigFootSightingRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;

class MainController extends AbstractController
{
    #[Route('/', name:'app_homepage')]
    public function homepage(BigFootSightingRepository $bigFootSightingRepository)
    {
        $sightings = $this->createSightingsPaginator(1, $bigFootSightingRepository);

        return $this->render('main/homepage.html.twig', [
            'sightings' => $sightings
        ]);
    }

    #[Route('/_sightings', name:'app_sightings_partial_list')]
    public function loadSightingsPartial(BigFootSightingRepository $bigFootSightingRepository, Request $request)
    {
        // simple pagination!
        $page = $request->query->get('page', 1);
        $sightings = $this->createSightingsPaginator($page, $bigFootSightingRepository);

        $html = $this->renderView('main/_sightings.html.twig', [
            'sightings' => $sightings
        ]);

        $data = [
            'html' => $html,
            'next' => count($sightings) > 0 ? ++$page : null,
        ];

        return $this->json($data);
    }

    #[Route('/api/github-organization', name:'app_github_organization_info')]
    public function gitHubOrganizationInfo(GitHubApiHelper $apiHelper)
    {
        $organizationName = 'SymfonyCasts';
        $organization = $apiHelper->getOrganizationInfo($organizationName);
        $repositories = $apiHelper->getOrganizationRepositories($organizationName);

        return $this->json([
            'organization' => $organization,
            'repositories' => $repositories,
        ]);
    }

    #[Route('/sighting/{id}', name:'app_sighting_show')]
    public function showSighting(BigFootSighting $bigFootSighting)
    {
        return $this->render('main/sighting_show.html.twig', [
            'sighting' => $bigFootSighting
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     */
    #[Route('/terms/updated', name:'agree_terms_update')]
    public function agreeUpdatedTerms(Request $request, EntityManagerInterface $entityManager)
    {
        $form = $this->createForm(AgreeToUpdatedTermsFormType::class);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var User $user */
            $user = $this->getUser();
            $user->setAgreedToTermsAt(new \DateTimeImmutable());
            $entityManager->flush();

            return $this->redirect(
                $request->headers->get('Referer') ?: $this->generateUrl('app_homepage')
            );
        }

        return $this->render('main/agreeUpdatedTerms.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/about', name:'app_about')]
    public function about()
    {
        return $this->render('main/about.html.twig');
    }

    /**
     * @return Paginator|BigFootSighting[]
     */
    private function createSightingsPaginator(int $page, BigFootSightingRepository $bigFootSightingRepository): Paginator
    {
        $maxResults = 25;
        $qb = $bigFootSightingRepository->findLatestQueryBuilder($maxResults);
        $qb->setFirstResult($maxResults * ($page - 1));

        return new Paginator($qb);
    }
}

templates/main/_sightings.html.twig
{% for sighting in sightings %}
<tr>
    <td>
        <a class="text-white" href="{{ path('app_sighting_show', {id: sighting.id}) }}">
            {{ sighting.title }}
        </a>
    </td>
    <td class="text-nowrap">
        <time class="table-content" datetime="{{ sighting.createdAt|date('Y-m-d H:i') }}">{{ sighting.createdAt|time_diff }}</time>
    </td>
    <td>
        <a class="text-white table-content text-center" href="{{ path('app_sighting_show', {id: sighting.id}) }}">{{ sighting.comments|length }}</a>
    </td>
</tr>
{% endfor %}

templates/main/about.html.twig
{% extends 'base.html.twig' %}

{% block title %}Aghh! I mean, hello.{% endblock %}


{% block body %}

<div class="col-3">
    <div>
        <img src="{{ asset('build/images/bigfoot.png') }}" class="big-foot-img" alt="sasquatch">
    </div>
</div>

<div class="col">
    <h1>About Us</h1>
    <p>
        We are definitely real "humans" and not sasquatch hiding in plain site. 
        We enjoy doing many popular human things, such as "showering under
        warm water" and "moving a brush on top of our teeth".
        We definitely do not enjoy hiding from other humans nor hunting
        with our bare claws, I mean, hands.
    </p>
</div>
{% endblock %}

templates/main/agreeUpdatedTerms.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="col mb-5">
    <h2 style="font-size: 1.5rem;">We have updated our terms</h2>

    <div>
        Updated terms: by using this site, you agree that
        BigFoot *might* exist.
    </div>
    
    {{ form_start(form, {
            attr: {
                action: path('agree_terms_update')
            }
        }) }}
        {{ form_row(form) }}
        <button class="btn btn-info" type="submit">Submit</button>
    {{ form_end(form) }}
</div>
{% endblock %}

templates/main/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="col-8">
    <h3>Recently Reported Sightings</h3>
    <small>Submit yours to help us narrow down this search</small>
    <table class="table table-striped table-dark table-borderless table-hover">
        <thead>
            <tr class="bg-info">
                <th>Sighting Details</th>
                <th>Posted</th>
                <th>Comments</th>
            </tr>
        </thead>
        <tbody class="js-sightings-list" data-url="{{ path('app_sightings_partial_list') }}">
            {{ include('main/_sightings.html.twig') }}
        </tbody>
    </table>
</div>
<div class="col-4">
    <div class="js-github-organization" data-url="{{ path('app_github_organization_info') }}"></div>
</div>

{% endblock %}

templates/main/sighting_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ sighting.title }} | Bigfoot{% endblock %}

{% block body %}
<div class="col">
    <div class="sighting-log-container mb-5 pb-5">
        <h2 style="font-size: 1.5rem;">{{ sighting.title }}</h2>
        <p><span class="pr-2"><i class="fa fa-clock"></i> <time datetime="{{ sighting.createdAt|date('Y-m-d H:i') }}">{{ sighting.createdAt|time_diff }}</time></span>
            |
            <span class="pl-2">Big Foot Believability Score: <span class="badge badge-info">{{ sighting.score }}</span> </span>
        </p>
        <div>
            {{ sighting.description }}
        </div>
    </div>

    <h3>Littlefoot (i.e. Human) Reactions</h3>
    
    {% for comment in sighting.comments %}
        <div class="comment-container mb-3">
            <div class="row">
                <div class="col-1">        
                    <img class="px-1 py-1" src="{{ comment.owner.avatarUrl }}" alt="Avatar for {{ comment.owner.username }}">
                </div>
                <div class="col">
                    <strong>{{ comment.owner.username }}</strong>
                    <span>({{ comment.owner|user_activity_text }})</span>
                    <span class="px-2">|</span>
                    <small><i class="fa fa-clock pr-2"></i><time datetime="{{ comment.createdAt|date('Y-m-d H:i') }}">{{ comment.createdAt|time_diff }}</time></small>
                    <div class="pt-2">
                        {{ comment.content }}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    
</div>
{% endblock %}